package com.agentplatform.codereview.service;

import com.agentplatform.codereview.model.CodeReviewIssue;
import com.agentplatform.codereview.model.CodeReviewReport;
import com.agentplatform.codereview.model.JavaFileSnapshot;
import com.agentplatform.codereview.model.Severity;
import org.springframework.stereotype.Component;

import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Renders a code review report as structured Markdown.
 */
@Component
public class MarkdownReportGenerator {

    public String generate(CodeReviewReport report) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Java Code Review Report\n\n");
        appendMetadata(sb, report);
        appendSummary(sb, report);
        appendFileTable(sb, report);
        appendIssues(sb, report);
        appendLlmInsight(sb, report);
        sb.append("\n---\n");
        sb.append("Generated by java-agent-platform code_review_agent at ")
                .append(report.getCreatedAt())
                .append("\n");
        return sb.toString();
    }

    private void appendMetadata(StringBuilder sb, CodeReviewReport report) {
        sb.append("| Item | Value |\n");
        sb.append("| --- | --- |\n");
        sb.append("| Report ID | ").append(report.getReportId()).append(" |\n");
        sb.append("| Task ID | ").append(report.getTaskId()).append(" |\n");
        sb.append("| Repository | ").append(report.getRepoPath()).append(" |\n");
        sb.append("| Branch | ").append(report.getBranch()).append(" |\n");
        sb.append("| HEAD | ").append(report.getHeadCommit()).append(" |\n");
        sb.append("| Diff base | ").append(nvl(report.getDiffBase(), "HEAD")).append(" |\n");
        sb.append("| Analyzed files | ").append(report.getAnalyzedFileCount()).append(" |\n");
        sb.append("| Total tracked Java files | ").append(report.getTotalJavaFiles()).append(" |\n");
        sb.append("| Total lines | ").append(report.getTotalLines()).append(" |\n");
        sb.append("| Issues | ").append(report.getIssueCount()).append(" |\n");
        sb.append("| LLM enhanced | ").append(report.isLlmEnabled()).append(" |\n\n");
    }

    private void appendSummary(StringBuilder sb, CodeReviewReport report) {
        sb.append("## Summary\n\n");
        sb.append(report.getSummary()).append("\n\n");
    }

    private void appendFileTable(StringBuilder sb, CodeReviewReport report) {
        List<JavaFileSnapshot> files = report.getFiles();
        if (files.isEmpty()) {
            sb.append("## Files\n\nNo Java files were analyzed.\n\n");
            return;
        }
        sb.append("## Files\n\n");
        sb.append("| File | Class | Lines | Methods | Complexity | Issues |\n");
        sb.append("| --- | --- | ---: | ---: | ---: | ---: |\n");
        for (JavaFileSnapshot file : files) {
            sb.append("| ").append(file.relativePath())
                    .append(" | ").append(file.className())
                    .append(" | ").append(file.lineCount())
                    .append(" | ").append(file.methodCount())
                    .append(" | ").append(file.complexity())
                    .append(" | ").append(file.issues().size())
                    .append(" |\n");
        }
        sb.append("\n");
    }

    private void appendIssues(StringBuilder sb, CodeReviewReport report) {
        sb.append("## Issues\n\n");
        if (report.getIssues().isEmpty()) {
            sb.append("No rule-based issues found.\n\n");
            return;
        }

        Map<String, List<CodeReviewIssue>> byFile = report.getIssues().stream()
                .sorted(Comparator.comparing(CodeReviewIssue::severity)
                        .thenComparingInt(CodeReviewIssue::line))
                .collect(Collectors.groupingBy(CodeReviewIssue::filePath));

        for (Map.Entry<String, List<CodeReviewIssue>> entry : byFile.entrySet()) {
            sb.append("### ").append(entry.getKey()).append("\n\n");
            for (CodeReviewIssue issue : entry.getValue()) {
                sb.append("- **[").append(issue.severity()).append("]** ")
                        .append("line ").append(issue.line()).append(" | ")
                        .append(issue.rule()).append(" | ")
                        .append(issue.message())
                        .append("\n");
            }
            sb.append("\n");
        }
    }

    private void appendLlmInsight(StringBuilder sb, CodeReviewReport report) {
        sb.append("## AI Insights\n\n");
        if (report.isLlmEnabled() && report.getLlmInsight() != null && !report.getLlmInsight().isBlank()) {
            sb.append(report.getLlmInsight()).append("\n\n");
        } else {
            sb.append("LLM review was not enabled. Configure `LLM_API_KEY` to enable AI insights.\n\n");
        }
    }

    private String nvl(String value, String fallback) {
        return value == null || value.isBlank() ? fallback : value;
    }
}
